### ISSUE TITLE
Add colour and formatting to all messages

### ISSUE THREAD

**Issue by andyksaw** [projectcitybuild/PCBridge#15]
All messages sent in chat to the player are all currently white.

**Comment by Mannriah** [comment]
Are they not supposed to be white?

**Comment by andyksaw** [comment]
Errors should be red, success should be green, etc.

If everything is white it might get lost in the sea of chat

**Comment by Mannriah** [comment]
Ahh sorry I misunderstood! Makes sense!

**Comment by andyksaw** [comment]
Will be fixed by https://github.com/projectcitybuild/PCBridge/pull/36
