### ISSUE TITLE
Add confirmation links to commands

### ISSUE THREAD

**Issue by andyksaw** [projectcitybuild/PCBridge#16]
## Issue
Currently if you ban a player (`/ban <name>`), it executes immediately. 

## Solution
It would be better if the server sent a confirmation message first: *Are you sure you want to ban _____?*, and provide a clickable option to actually execute the ban command.

**Comment by Mannriah** [comment]
Rather than a clickable option, I've noticed a few plugins list commands that can be typed to e.g. "/yes, /no, /help"

**Comment by freddyheppell** [comment]
I'm not _entirely_ sure this is necessary, banning isn't destructive as we can always unban if it was a mistake. If we do have confirmations I'd rather it was a global `/yes`, `/no` command for everywhere that requires confirmations.
