### ISSUE TITLE
Enhancements and additional commands/features

### ISSUE THREAD

**Issue by manningtelfer** [projectcitybuild/PCBridge#44]
General list, will edit/ammend over time.

# General UX enhancements
- [x] Tab autocompletion for all commands with syntax
- [x] Partial-completed text matching (e.g. /tp andy would match to _andy)
- [ ] /pcbridge (or /pcbridge version) - shows plugin name and version
- [ ] /pcbridge help - help command, list of all commands and summary of their function

# Commands/features
## AFK
- [ ] /afk - toggle afk status on off, send message in chat to other self and other users (Automatically toggle on after 10 minutes of inactivity) - #105

## Bans
- [x] /ipban - ban a specific IP address
- [x] /unbanip - unban a specific IP address

## Chat
- [ ] /mail send <player/> - sends mail to the specified user or wildcard ( for online users, ** for all users) - #107
- [ ] /mail read - outputs mail from inbox to user
- [ ] /mail clear - removes all mail in inbox

## Warps
- [x] Alphabetise warp list, currently seems to be random.
- [x] Fix pagination, has a page 0 randomly appear sometimes
- [ ] Wrap warp name if it overflows a line in warp list
- [ ] #106
- [x] Clickable warps in warp list (wishlist)

## Teleporting
- [x] /back - go back to previous location, regardless of world (Would be good if we could store a history of maybe 5 previous locations, so you could go back multiple times), further enhancement would be to allow the syntax /back <#> to navigate back multiple times in a single command.
- [ ] /forward - go forward to location, regardless of world (utilising the history from the /back command, allow users to go forward after using /back), further enhancement would be to allow the syntax /forward <#> to navigate forward multiple times in a single command.
- [x] /tptoggle - enable disable ability for players to teleport to you
- [x] /tpo - staff command to override disabled TP
- [x] /tpohere - staff command to override disabled TP

## Staff tools (Wishlist!)
* /ping - responds with "Pong!" and the round trip time in milliseconds
* /seen - shows whether a user is online or offline as well as the specified time online or offline. Also shows UUID, location (country), IP address and if the user is currently banned, outputs this in seperate lines to user
* /whois - shows a users nickname, UUID, health, hunger, Exp, Location (Server, World, X, Y, Z), playtime, money, IP address, Location (country), gamemode, god mode (true/false), OP (true,false), fly mode (true, false)
* /sudo <user> <command> - issue commands on behalf of a player automatically prefixes with a beggining forward slash (e.g. entering "/sudo Mannriah ping" would force the player Mannriah to run "/ping". Additionally, training slash can be escaped by entering "c:", e.g. entering "/sudo Mannriah c:Hello!" would force the player Mannriah to output "Hello!" in chat, rather than running a command.

**Comment by andyksaw** [comment]
Closing in favour of individual issues
