### ISSUE TITLE
Auto generate `bungee.yml` and `plugin.yml`

### ISSUE THREAD

**Issue by andyksaw** [projectcitybuild/PCBridge#63]
Use annotations to generate `bungee.yml` (Bungeecord) and `plugin.yml` (Spigot). It's annoying to have to define the commands, etc again inside a YAML file

**Comment by freddyheppell** [comment]
There is a Gradle plugin which does some automation like this for you. I'll see if I can find it again.

**Comment by freddyheppell** [comment]
Some options on the Spigot wiki here: https://www.spigotmc.org/wiki/spigot-gradle/#generators

**Comment by andyksaw** [comment]
Unfortunately the ones listed there are just reading the values from the `gradle.build` file and generating an `xxx.yml` file from it. 
It doesn't solve the problem because the values have to be written twice (once in code and again in `gradle.build`).

I was thinking of using annotations and an annotation processor to generate the file, because all these values are already available in code.

For example...
```swift
@Command
class TPCommand { 

    @CommandLabel
    private var label = "tp"

    ...
}
```

**Comment by andyksaw** [comment]
I believe something already exists like this for Spigot, but I've never managed to find an equivalent for Bungeecord
